# Generated by Django 5.2.1 on 2026-02-18 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reg_no', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3')], max_length=1)),
                ('meal', models.CharField(choices=[('snacks', 'Snacks'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.participant')),
            ],
            options={
                'unique_together': {('participant', 'day', 'meal')},
            },
        ),
    ]
