# Generated by Django 5.2.1 on 2026-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealscan',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mealscan',
            name='meal',
            field=models.CharField(max_length=20),
        ),
    ]
